# Generated by Django 5.0.14 on 2026-09-21 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioSENA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convenio', models.CharField(max_length=50, unique=True, verbose_name='Número o Código del Convenio')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Convenio')),
                ('tipo_convenio', models.CharField(choices=[('Articulacion Media Tecnica', 'Articulación Media Técnica'), ('Pasantias y Practicas', 'Pasantías y Prácticas'), ('Marco de Cooperacion', 'Marco de Cooperación'), ('Especifico', 'Convenio Específico'), ('Comodato', 'Comodato de Equipos e Infraestructura'), ('Otro', 'Otro Convenio')], default='Articulacion Media Tecnica', max_length=80, verbose_name='Tipo de Convenio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Convenio')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo del Convenio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('responsable', models.CharField(max_length=150, verbose_name='Responsable SENA / Institucional')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado_manual', models.CharField(blank=True, choices=[('Suspendido', 'Suspendido'), ('Finalizado', 'Finalizado')], max_length=20, null=True, verbose_name='Estado Forzado / Manual (Opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Convenio SENA',
                'verbose_name_plural': 'Convenios SENA',
                'ordering': ['-fecha_fin', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InstitucionConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Institución')),
                ('codigo_dane', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código DANE')),
                ('departamento', models.CharField(default='Magdalena', max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto')),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono del Contacto')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Institución Activa?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='convenios/logos/%Y/%m/', verbose_name='Logo Institucional')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Institución')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Institución de Convenio',
                'verbose_name_plural': 'Instituciones de Convenios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='convenios/documentos/%Y/%m/', verbose_name='Archivo Digital')),
                ('tipo', models.CharField(choices=[('Documento del convenio', 'Documento del convenio'), ('Acta', 'Acta'), ('Certificación', 'Certificación'), ('Documento institucional', 'Documento institucional'), ('Otros', 'Otros')], default='Documento del convenio', max_length=50, verbose_name='Tipo de Documento')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Documento')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convenios.conveniosena', verbose_name='Convenio Asociado')),
                ('usuario_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_convenios_sena', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cargó el documento')),
            ],
            options={
                'verbose_name': 'Documento de Convenio',
                'verbose_name_plural': 'Documentos de Convenios',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='conveniosena',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='convenios.institucionconvenio', verbose_name='Institución Educativa'),
        ),
    ]
