# Generated by Django 5.0.14 on 2026-09-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
        ('instituciones', '0003_institucioneducativa_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosena',
            name='institucion_educativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convenios_sena', to='instituciones.institucioneducativa', verbose_name='Institución Educativa Articulada'),
        ),
        migrations.CreateModel(
            name='BeneficioConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Beneficio')),
                ('tipo', models.CharField(choices=[('Cursos', 'Cursos de Formación'), ('Certificaciones', 'Certificaciones Técnicas'), ('Acceso a Programas', 'Acceso Preferencial a Programas'), ('Formación Complementaria', 'Formación Complementaria Especial'), ('Actividades', 'Actividades / Talleres de Innovación'), ('Orientación', 'Orientación Ocupacional y Empleo'), ('Beneficios Especiales', 'Beneficios Especiales / Dotación'), ('Otro', 'Otro Beneficio')], default='Cursos', max_length=60, verbose_name='Tipo de Beneficio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción y Alcance')),
                ('cantidad_cupos', models.PositiveIntegerField(default=30, verbose_name='Cupos Estimados / Población Beneficiaria')),
                ('estado', models.CharField(choices=[('Activo', 'Activo / Disponible'), ('En Ejecución', 'En Ejecución'), ('Cumplido', 'Cumplido / Culminado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=30, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='convenios.conveniosena', verbose_name='Convenio SENA')),
            ],
            options={
                'verbose_name': 'Beneficio de Convenio',
                'verbose_name_plural': 'Beneficios de Convenios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
