# Generated by Django 5.0.14 on 2026-09-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuicioEvaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juicio_valor', models.CharField(choices=[('A', 'A - Aprobado (Alcanzó los criterios de desempeño)'), ('D', 'D - No Aprobado (Requiere plan de mejoramiento / No alcanzado)')], max_length=1, verbose_name='Juicio de Valor Cualitativo')),
                ('observaciones', models.TextField(blank=True, help_text="Recomendado especialmente cuando el juicio es 'D' (No Aprobado).", null=True, verbose_name='Retroalimentación Pedagógica')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de la Evaluación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo del Registro (Auditoría)')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='juicios_asentados', to=settings.AUTH_USER_MODEL, verbose_name='Instructor Evaluador')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios_evaluativos', to='academico.matricula', verbose_name='Aprendiz Matriculado')),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='juicios_emitidos', to='academico.resultadoaprendizaje', verbose_name='Resultado de Aprendizaje (RAP)')),
            ],
            options={
                'verbose_name': 'Juicio Evaluativo',
                'verbose_name_plural': 'Juicios Evaluativos',
                'ordering': ['matricula', 'resultado_aprendizaje__codigo'],
                'unique_together': {('matricula', 'resultado_aprendizaje')},
            },
        ),
    ]
