# Generated by Django 5.0.14 on 2026-09-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programa', models.CharField(help_text='Código oficial curricular nacional.', max_length=20, unique=True, verbose_name='Código del Programa (SOFIA)')),
                ('denominacion', models.CharField(max_length=200, verbose_name='Denominación del Programa')),
                ('version', models.CharField(default='1', max_length=10, verbose_name='Versión Curricular')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Programa Activo?')),
            ],
            options={
                'verbose_name': 'Programa de Formación',
                'verbose_name_plural': 'Programas de Formación',
                'ordering': ['denominacion'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ficha', models.CharField(help_text='Número identificador asignado al grupo en el Centro.', max_length=20, unique=True, verbose_name='Número de Ficha')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio Lectivo')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Estimada de Finalización')),
                ('estado', models.CharField(choices=[('En Ejecucion', 'En Ejecución'), ('Terminada', 'Terminada'), ('Cancelada', 'Cancelada')], default='En Ejecucion', max_length=20, verbose_name='Estado de la Ficha')),
                ('periodo_cerrado', models.BooleanField(default=False, help_text='Si está marcado, se bloquea el registro y edición de calificaciones.', verbose_name='¿Periodo Evaluativo Cerrado Formalmente?')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='instituciones.institucioneducativa', verbose_name='Institución Educativa Articulada')),
                ('instructor_lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Instructor Líder Responsable')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='academico.programaformacion', verbose_name='Programa Técnico')),
            ],
            options={
                'verbose_name': 'Ficha de Media Técnica',
                'verbose_name_plural': 'Fichas de Media Técnica',
                'ordering': ['-fecha_inicio', 'codigo_ficha'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de la Norma / Competencia')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Competencia')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='academico.programaformacion', verbose_name='Programa de Formación')),
            ],
            options={
                'verbose_name': 'Competencia Laboral',
                'verbose_name_plural': 'Competencias Laborales',
                'ordering': ['programa', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código del RAP')),
                ('descripcion', models.TextField(verbose_name='Descripción del Resultado de Aprendizaje')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='academico.competencia', verbose_name='Competencia Asociada')),
            ],
            options={
                'verbose_name': 'Resultado de Aprendizaje',
                'verbose_name_plural': 'Resultados de Aprendizaje',
                'ordering': ['competencia', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('grado_escolar', models.CharField(choices=[('10', 'Grado 10° (Décimo)'), ('11', 'Grado 11° (Undécimo)')], default='10', max_length=5, verbose_name='Grado Escolar en el Colegio')),
                ('estado_formacion', models.CharField(choices=[('En Formacion', 'En Formación'), ('Desertado', 'Desertado'), ('Trasladado', 'Trasladado'), ('Retirado', 'Retiro Voluntario'), ('Certificado', 'Certificado')], default='En Formacion', max_length=25, verbose_name='Estado de la Formación')),
                ('acudiente_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Padre o Acudiente')),
                ('acudiente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Acudiente')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_academicas', to=settings.AUTH_USER_MODEL, verbose_name='Aprendiz')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.ficha', verbose_name='Ficha Asignada')),
            ],
            options={
                'verbose_name': 'Matrícula de Aprendiz',
                'verbose_name_plural': 'Matrículas de Aprendices',
                'ordering': ['ficha', 'aprendiz__last_name'],
                'unique_together': {('ficha', 'aprendiz')},
            },
        ),
    ]
