# Generated by Django 4.2.10 on 2026-09-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ambiente', models.CharField(blank=True, max_length=120)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20)),
                ('tema', models.CharField(blank=True, max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.ficha')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_formativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
    ]
