# Generated by Django 5.0.14 on 2026-09-17 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_horarioficha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('Permuta', 'Permuta consensuada de bloque'), ('Incapacidad', 'Incapacidad médica / Reemplazo temporal'), ('Acompanamiento', 'Acompañamiento pedagógico con Docente I.E.'), ('Sesion_Especial', 'Sesión técnica transversal / Taller'), ('Ajuste_Horario', 'Ajuste de jornada institucional')], default='Permuta', max_length=30, verbose_name='Motivo de la Novedad')),
                ('observacion', models.TextField(blank=True, verbose_name='Detalles o Acuerdos Pedagógicos')),
                ('fecha_novedad', models.DateField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='academico.horarioficha', verbose_name='Bloque de Horario')),
                ('instructor_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_cedidos', to=settings.AUTH_USER_MODEL, verbose_name='Instructor/Docente Anterior')),
                ('instructor_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Instructor/Docente Asignado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Novedad de Horario',
                'verbose_name_plural': 'Novedades de Horario',
                'ordering': ['-fecha_novedad', '-id'],
            },
        ),
    ]
