# Generated by Django 5.0.14 on 2026-09-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_novedadhorario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovedadHorario',
        ),
    ]
