# Generated by Django 5.0.14 on 2026-09-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_delete_novedadhorario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioficha',
            options={'ordering': ['dia', 'hora_inicio'], 'verbose_name': 'Horario de Ficha', 'verbose_name_plural': 'Horarios de Fichas'},
        ),
    ]
