# Generated by Django 5.0.14 on 2026-09-19 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_horarioficha_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Título del Recurso')),
                ('autor', models.CharField(default='SENA Regional Magdalena', max_length=160, verbose_name='Autor / Entidad')),
                ('categoria', models.CharField(choices=[('Libro Tecnico', 'Libro Técnico'), ('Manual SENA', 'Manual SENA'), ('Guia de Aprendizaje', 'Guía de Aprendizaje'), ('Diseno Curricular', 'Diseño Curricular SOFIA'), ('Documento Tecnico', 'Documento Técnico / Estándar'), ('Publicacion', 'Publicación Académica')], default='Guia de Aprendizaje', max_length=40)),
                ('tipo_recurso', models.CharField(default='Documento Digital PDF', max_length=60)),
                ('descripcion', models.TextField(verbose_name='Descripción y Contenido')),
                ('ano_publicacion', models.IntegerField(default=2026, verbose_name='Año de Publicación')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='biblioteca_recursos/%Y/')),
                ('url_externa', models.URLField(blank=True, null=True, verbose_name='Enlace de Consulta Externa')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para Descarga')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_biblioteca', to='academico.programaformacion')),
            ],
            options={
                'verbose_name': 'Recurso de Biblioteca',
                'verbose_name_plural': 'Recursos de Biblioteca',
                'ordering': ['-ano_publicacion', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='RecursoGuardadoAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_guardados', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados_por', to='academico.recursobiblioteca')),
            ],
            options={
                'verbose_name': 'Recurso Guardado por Aprendiz',
                'verbose_name_plural': 'Recursos Guardados por Aprendices',
                'ordering': ['-fecha_guardado'],
                'unique_together': {('aprendiz', 'recurso')},
            },
        ),
    ]
