# Generated by Django 5.0.14 on 2026-09-19 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_recursobiblioteca_recursoguardadoaprendiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Título del Documento')),
                ('categoria', models.CharField(choices=[('Formato Oficial SENA', 'Formato Oficial SENA (PE-04 / F023)'), ('Guia Pedagogica', 'Guía de Aprendizaje Pedagógica'), ('Acta de Comite', 'Acta de Comité de Evaluación'), ('Paz y Salvo', 'Paz y Salvo y Certificaciones'), ('Normativa Institucional', 'Normativa y Circulares del Centro')], default='Formato Oficial SENA', max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Contenido')),
                ('archivo', models.FileField(upload_to='gestion_documental/%Y/%m/', verbose_name='Archivo Digital (PDF / Word / Excel)')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versión')),
                ('roles_permitidos', models.CharField(default='Todos', help_text="Escribir 'Todos' o roles separados por coma: Ej: Coordinador,Instructor SENA,Secretaría", max_length=255, verbose_name='Roles Autorizados')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Funcionario que Publica')),
            ],
            options={
                'verbose_name': 'Documento Institucional',
                'verbose_name_plural': 'Documentos Institucionales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='LogroAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Nombre de la Insignia')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Mérito Reconocido')),
                ('icono', models.CharField(default='bi-trophy-fill', max_length=60, verbose_name='Icono Bootstrap')),
                ('color', models.CharField(default='success', max_length=30, verbose_name='Color de la Insignia')),
                ('categoria', models.CharField(default='Puntualidad y Asistencia', max_length=50, verbose_name='Categoría')),
                ('fecha_otorgado', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_obtenidos', to=settings.AUTH_USER_MODEL, verbose_name='Aprendiz Destacado')),
            ],
            options={
                'verbose_name': 'Logro / Insignia Formativa',
                'verbose_name_plural': 'Logros e Insignias Formativas',
                'ordering': ['-fecha_otorgado'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoInnovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Título del Proyecto / Idea')),
                ('descripcion', models.TextField(verbose_name='Descripción, Justificación e Impacto')),
                ('categoria', models.CharField(choices=[('Software TIC', 'Desarrollo de Software y TIC'), ('Agroecologia', 'Agroecología y Biotecnología'), ('Ecoturismo', 'Ecoturismo y Hotelería Regional'), ('Logistica', 'Logística y Comercio Portuario'), ('Emprendimiento', 'Emprendimiento Comunitario')], default='Software TIC', max_length=50, verbose_name='Línea Tecnológica')),
                ('estado', models.CharField(choices=[('IDEA', 'Idea en Conceptualización'), ('PROPUESTA', 'Propuesta Radicada'), ('EN_EVALUACION', 'En Evaluación de Comité'), ('EN_DESARROLLO', 'En Desarrollo Activo'), ('FINALIZADO', 'Proyecto Finalizado / Transferido')], default='IDEA', max_length=30, verbose_name='Estado de Madurez')),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='proyectos_innovacion/%Y/%m/', verbose_name='Ficha Técnica o Documento de Propuesta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_innovacion', to='academico.ficha', verbose_name='Ficha Formativa')),
                ('instructor_asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_innovacion_asesorados', to=settings.AUTH_USER_MODEL, verbose_name='Instructor Asesor Técnico')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_innovacion_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Aprendiz / Instructor Líder')),
            ],
            options={
                'verbose_name': 'Proyecto de Innovación',
                'verbose_name_plural': 'Proyectos de Innovación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
