# Generated by Django 5.0.14 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_documentoinstitucional_logroaprendiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioficha',
            name='dia',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes')], max_length=1),
        ),
    ]
