# Generated by Django 5.0.14 on 2026-09-22 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alter_horarioficha_dia'),
        ('convenios', '0001_initial'),
        ('instituciones', '0003_institucioneducativa_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programaformacion',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_asociados', to='convenios.conveniosena', verbose_name='Convenio SENA Vinculado'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=880, verbose_name='Intensidad Horaria Total (Horas)'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='duracion_meses',
            field=models.PositiveIntegerField(default=12, verbose_name='Duración Estimada (Meses)'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_articulados', to='instituciones.institucioneducativa', verbose_name='Colegio / Institución Sede'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Curriculares'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable / Instructor Líder'),
        ),
        migrations.AddField(
            model_name='programaformacion',
            name='tipo_programa',
            field=models.CharField(choices=[('Técnico', 'Técnico Laboral / Media Técnica'), ('Tecnólogo', 'Tecnólogo'), ('Curso Especial', 'Curso Especial'), ('Formación Complementaria', 'Formación Complementaria'), ('Otro', 'Otro Programa')], default='Técnico', max_length=50, verbose_name='Tipo de Formación'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='instructor_lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor Líder Responsable'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_academicas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.CreateModel(
            name='SemaforoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('RECUPERAR', 'Por recuperar')], default='EN_PROCESO', max_length=20, verbose_name='Estado del Semáforo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Pedagógicas / Plan de Mejora')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_semaforo', to='academico.competencia', verbose_name='Competencia Laboral')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaforo_competencias', to='academico.matricula', verbose_name='Estudiante Matriculado')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_semaforo', to=settings.AUTH_USER_MODEL, verbose_name='Profesor / Evaluador')),
                ('resultado_aprendizaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_semaforo', to='academico.resultadoaprendizaje', verbose_name='Resultado de Aprendizaje (RAP)')),
            ],
            options={
                'verbose_name': 'Semáforo de Competencia',
                'verbose_name_plural': 'Semáforo de Competencias',
                'ordering': ['matricula', 'competencia', 'resultado_aprendizaje'],
                'unique_together': {('matricula', 'competencia', 'resultado_aprendizaje')},
            },
        ),
    ]
