# Generated by Django 5.0.14 on 2026-09-24 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_programaformacion_convenio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioficha',
            name='es_recreo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horarioficha',
            name='grado',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='horarioficha',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horarioficha',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='academico.programaformacion', verbose_name='Materia / Curso'),
        ),
        migrations.AddField(
            model_name='horarioficha',
            name='seccion',
            field=models.CharField(blank=True, default='A', max_length=4),
        ),
        migrations.AlterField(
            model_name='horarioficha',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='academico.ficha'),
        ),
        migrations.AlterField(
            model_name='horarioficha',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_formativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20)),
                ('grado', models.CharField(max_length=40)),
                ('seccion', models.CharField(default='A', max_length=4)),
                ('anio_lectivo', models.PositiveIntegerField(default=2026)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.programaformacion')),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
                'ordering': ['nivel', 'grado', 'programa__denominacion'],
                'unique_together': {('profesor', 'programa', 'nivel', 'grado', 'seccion', 'anio_lectivo')},
            },
        ),
    ]
