# Generated by Django 5.0.14 on 2026-09-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_horario_escolar_y_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='seccion',
            field=models.CharField(default='A', max_length=4, verbose_name='Sección Escolar'),
        ),
    ]
