# Generated by Django 5.0.14 on 2026-09-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_matricula_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='grado_escolar',
            field=models.CharField(choices=[('1', '1° Grado (Primaria)'), ('2', '2° Grado (Primaria)'), ('3', '3° Grado (Primaria)'), ('4', '4° Grado (Primaria)'), ('5', '5° Grado (Primaria)'), ('6', '6° Grado (Secundaria)'), ('7', '7° Grado (Secundaria)'), ('8', '8° Grado (Secundaria)'), ('9', '9° Grado (Secundaria)'), ('10', '10° Grado (Bachillerato)'), ('11', '11° Grado (Bachillerato)')], default='10', max_length=5, verbose_name='Grado Escolar en el Colegio'),
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Objetivo')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='academico.competencia', verbose_name='Competencia Asociada')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
    ]
