# Generated by Django 5.0.14 on 2026-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_matricula_grado_escolar_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioficha',
            name='color_hex',
            field=models.CharField(blank=True, default='#E2E8F0', max_length=7, verbose_name='Color del Bloque'),
        ),
    ]
