# Generated by Django 5.0.14 on 2026-09-28 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_horarioficha_color_hex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actividades_clase/%Y/%m/')),
                ('fecha_actividad', models.DateTimeField(blank=True, null=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.cargaacademica')),
            ],
            options={
                'verbose_name': 'Actividad de Clase',
                'verbose_name_plural': 'Actividades de Clase',
            },
        ),
        migrations.CreateModel(
            name='AvisoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='academico.cargaacademica')),
            ],
            options={
                'verbose_name': 'Aviso de Clase',
                'verbose_name_plural': 'Avisos de Clase',
            },
        ),
        migrations.CreateModel(
            name='GuiaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='guias_clase/%Y/%m/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='academico.cargaacademica')),
            ],
            options={
                'verbose_name': 'Guía de Clase',
                'verbose_name_plural': 'Guías de Clase',
            },
        ),
        migrations.CreateModel(
            name='MaterialClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales_clase/%Y/%m/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academico.cargaacademica')),
            ],
            options={
                'verbose_name': 'Material de Clase',
                'verbose_name_plural': 'Materiales de Clase',
            },
        ),
        migrations.CreateModel(
            name='TareaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas_clase/%Y/%m/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academico.cargaacademica')),
            ],
            options={
                'verbose_name': 'Tarea de Clase',
                'verbose_name_plural': 'Tareas de Clase',
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas_tareas/%Y/%m/')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('ENTREGADA_TARDE', 'Entregada fuera de plazo'), ('CALIFICADA', 'Calificada')], default='PENDIENTE', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_entregadas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academico.tareaclase')),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
