# Generated by Django 5.0.14 on 2026-09-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_actividadclase_avisoclase_guiaclase_materialclase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaclase',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_clase', to='academico.competencia', verbose_name='Competencia Evaluada'),
        ),
        migrations.AddField(
            model_name='tareaclase',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_clase', to='academico.objetivo', verbose_name='Objetivo Evaluado'),
        ),
        migrations.AddField(
            model_name='tareaclase',
            name='resultado_aprendizaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_clase', to='academico.resultadoaprendizaje', verbose_name='Resultado de Aprendizaje'),
        ),
        migrations.AddField(
            model_name='tareaclase',
            name='tipo_actividad',
            field=models.CharField(default='Tarea', max_length=50, verbose_name='Tipo de Actividad'),
        ),
    ]
