# Generated by Django 5.0.14 on 2026-09-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_tareaclase_competencia_tareaclase_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaclase',
            name='criterio_evaluacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Criterio de Evaluación'),
        ),
    ]
