# Generated by Django 5.0.14 on 2026-09-29 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_tareaclase_criterio_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='Periodo 1', max_length=50)),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('desempeno', models.CharField(default='Básico', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('carga_academica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_escolares', to='academico.cargaacademica')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_escolares', to='academico.matricula')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación Escolar',
                'verbose_name_plural': 'Calificaciones Escolares',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddConstraint(
            model_name='calificacionescolar',
            constraint=models.UniqueConstraint(fields=('matricula', 'carga_academica', 'periodo'), name='calificacion_escolar_unica_periodo'),
        ),
    ]
