# Generated by Django 5.0.14 on 2026-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_calificacionescolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaclase',
            name='enlace_externo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Apoyo'),
        ),
        migrations.AddField(
            model_name='tareaclase',
            name='es_calificada',
            field=models.BooleanField(default=True, verbose_name='¿Es Calificada?'),
        ),
        migrations.AddField(
            model_name='tareaclase',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicada', 'Publicada'), ('Cerrada', 'Cerrada')], default='Publicada', max_length=20, verbose_name='Estado de la Actividad'),
        ),
        migrations.AddField(
            model_name='tareaclase',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('ENTREGADA_TARDE', 'Entregada fuera de plazo'), ('CALIFICADA', 'Calificada'), ('DEVUELTA', 'Devuelta')], default='PENDIENTE', max_length=20),
        ),
    ]
