# Generated by Django 5.0.14 on 2026-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_tareaclase_enlace_externo_tareaclase_es_calificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaclase',
            name='periodo',
            field=models.CharField(default='Periodo 1', max_length=50, verbose_name='Periodo Académico'),
        ),
    ]
