# Generated by Django 5.0.14 on 2026-09-30 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_tareaclase_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comunicaciones/%Y/%m/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
