# Generated by Django 5.0.14 on 2026-09-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_comunicacionmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacionmensaje',
            name='eliminado_por_destinatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comunicacionmensaje',
            name='eliminado_por_remitente',
            field=models.BooleanField(default=False),
        ),
    ]
