# Generated by Django 5.0.14 on 2026-09-15 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_qr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20, unique=True, verbose_name='Número de Ficha')),
                ('programa', models.CharField(max_length=150, verbose_name='Nombre del Programa (Técnico/Tecnólogo)')),
                ('jornada', models.CharField(choices=[('Diurna', 'Diurna'), ('Nocturna', 'Nocturna'), ('Mixta', 'Mixta')], default='Diurna', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código RAP')),
                ('descripcion', models.TextField(verbose_name='Descripción del Resultado de Aprendizaje')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raps', to='usuarios.fichasena')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Taller / Evidencia')),
                ('descripcion', models.TextField(verbose_name='Instrucciones de la Guía de Aprendizaje')),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha y Hora Límite de Entrega')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='usuarios.resultadoaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_entregado', models.FileField(blank=True, null=True, upload_to='talleres_aprendices/', verbose_name='Archivo del Taller')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('juicio_evaluativo', models.CharField(choices=[('A', 'Aprobado (A)'), ('D', 'Deficiente (D)'), ('PENDIENTE', 'Pendiente de Calificar')], default='PENDIENTE', max_length=10, verbose_name='Juicio Evaluativo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Retroalimentación del Instructor')),
                ('aprendiz', models.ForeignKey(limit_choices_to={'perfil__rol__nombre': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.evidenciataller')),
            ],
            options={
                'unique_together': {('evidencia', 'aprendiz')},
            },
        ),
    ]
