# Generated by Django 4.2.10 on 2026-09-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_fichasena_resultadoaprendizaje_evidenciataller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='qr_rotacion',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Día de rotación QR'),
        ),
    ]
