# Generated by Django 5.0.14 on 2026-09-19 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_recursobiblioteca_recursoguardadoaprendiz'),
        ('usuarios', '0004_perfilusuario_qr_rotacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacionevidencia',
            options={'verbose_name': 'Entrega y Calificación de Evidencia', 'verbose_name_plural': 'Entregas y Calificaciones de Evidencias'},
        ),
        migrations.AlterModelOptions(
            name='evidenciataller',
            options={'ordering': ['-fecha_asignacion', 'fecha_limite'], 'verbose_name': 'Actividad / Taller de Aprendizaje', 'verbose_name_plural': 'Actividades / Talleres de Aprendizaje'},
        ),
        migrations.AddField(
            model_name='calificacionevidencia',
            name='comentarios_aprendiz',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de la Entrega'),
        ),
        migrations.AddField(
            model_name='calificacionevidencia',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='evidenciataller',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AddField(
            model_name='evidenciataller',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_formativas', to='academico.ficha', verbose_name='Ficha Asociada'),
        ),
        migrations.AddField(
            model_name='evidenciataller',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_publicadas', to=settings.AUTH_USER_MODEL, verbose_name='Instructor Asignador'),
        ),
        migrations.AddField(
            model_name='evidenciataller',
            name='material_apoyo',
            field=models.FileField(blank=True, null=True, upload_to='material_talleres/%Y/%m/', verbose_name='Material Proporcionado por el Instructor'),
        ),
        migrations.AddField(
            model_name='evidenciataller',
            name='rap_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_talleres', to='academico.resultadoaprendizaje', verbose_name='RAP Curricular SOFIA'),
        ),
        migrations.AlterField(
            model_name='calificacionevidencia',
            name='juicio_evaluativo',
            field=models.CharField(choices=[('A', 'Aprobado (A)'), ('D', 'Deficiente (D)'), ('PENDIENTE', 'Pendiente de Calificar')], default='PENDIENTE', max_length=15, verbose_name='Juicio Evaluativo'),
        ),
        migrations.AlterField(
            model_name='evidenciataller',
            name='rap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='usuarios.resultadoaprendizaje'),
        ),
    ]
