# Generated by Django 5.0.14 on 2026-09-22 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_calificacionevidencia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciataller',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_publicadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor Asignador'),
        ),
        migrations.AlterField(
            model_name='evidenciataller',
            name='material_apoyo',
            field=models.FileField(blank=True, null=True, upload_to='material_talleres/%Y/%m/', verbose_name='Material Proporcionado por el Profesor'),
        ),
    ]
