# Generated by Django 5.0.14 on 2026-09-22 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_evidenciataller_instructor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Institución Educativa Técnica', max_length=200, verbose_name='Nombre de la Institución')),
                ('lema', models.CharField(blank=True, default='Ciencia, Innovación y Liderazgo para el Futuro', max_length=255, verbose_name='Lema Institucional')),
                ('codigo_dane', models.CharField(blank=True, default='147001000234', max_length=50, verbose_name='Código DANE')),
                ('nit', models.CharField(blank=True, default='891.780.123-4', max_length=50, verbose_name='NIT')),
                ('resolucion', models.CharField(blank=True, default='Resolución Oficial No. 0482 MEN', max_length=150, verbose_name='Resolución de Aprobación')),
                ('rector', models.CharField(blank=True, default='Dr. Roberto Carlos Mendoza', max_length=150, verbose_name='Nombre del Rector')),
                ('direccion', models.CharField(blank=True, default='Avenida Principal # 12-45', max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default='(605) 421-9988', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='contacto@colegio.edu.co', max_length=254, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(blank=True, default='https://www.colegio.edu.co', verbose_name='Sitio Web')),
                ('color_primario', models.CharField(default='#0F2942', max_length=20, verbose_name='Color Principal (Azul Petróleo)')),
                ('color_secundario', models.CharField(default='#3B82F6', max_length=20, verbose_name='Color Secundario (Azul Suave)')),
                ('color_acento', models.CharField(default='#EEF2FF', max_length=20, verbose_name='Color Acento (Lavanda Suave)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colegio/', verbose_name='Escudo o Logo del Colegio')),
            ],
            options={
                'verbose_name': 'Identidad y Configuración del Colegio',
                'verbose_name_plural': 'Identidad y Configuración del Colegio',
            },
        ),
        migrations.CreateModel(
            name='FamiliaAcudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_acudiente', models.CharField(max_length=150, verbose_name='Nombre Completo del Acudiente')),
                ('parentesco', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Tutor Legal', 'Tutor Legal'), ('Abuelo/a', 'Abuelo/a'), ('Tío/a', 'Tío/a'), ('Hermano/a', 'Hermano/a'), ('Otro', 'Otro')], default='Madre', max_length=50, verbose_name='Parentesco')),
                ('documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento de Identidad')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono de Contacto')),
                ('telefono_secundario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Secundario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Residencia')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación / Profesión')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Familiares')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='nucleo_familiar', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes a Cargo')),
            ],
            options={
                'verbose_name': 'Familia y Acudiente',
                'verbose_name_plural': 'Familias y Acudientes',
                'ordering': ['nombre_acudiente'],
            },
        ),
    ]
