# Generated by Django 5.0.14 on 2026-09-25 19:44

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_configuracioncolegio_familiaacudiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(default=usuarios.models.siguiente_numero_recibo, max_length=30, unique=True)),
                ('concepto', models.CharField(default='Pensión mensual', max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=30)),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_pension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
