# Generated by Django 5.0.14 on 2026-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_pagopension'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopension',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pension/%Y/%m/'),
        ),
    ]
