# Generated by Django 5.0.14 on 2026-09-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfilusuario_foto_perfil_perfilusuario_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('conductor', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=15)),
                ('costo_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
