# Generated by Django 5.0.14 on 2026-09-28 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_perfilusuario_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapeleraReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Matricula', 'Matrícula'), ('Horario', 'Clase / Horario'), ('Docente', 'Docente / Profesor'), ('Otro', 'Otro Registro')], default='Estudiante', max_length=30, verbose_name='Tipo de Elemento')),
                ('objeto_id', models.IntegerField(verbose_name='ID Original del Objeto')),
                ('titulo', models.CharField(max_length=200, verbose_name='Identificador / Nombre')),
                ('subtitulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Detalles')),
                ('datos_recuperacion', models.JSONField(blank=True, null=True, verbose_name='Snapshot de Datos')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, default='Eliminado desde panel administrativo')),
                ('restaurado', models.BooleanField(default=False)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento en Papelera',
                'verbose_name_plural': 'Papelera de Reciclaje',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
