# Generated by Django 5.0.14 on 2026-09-28 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_papelerareciclaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteruta',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='rutas_transporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
