# Generated by Django 5.0.14 on 2026-09-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_matricula_grado_escolar_objetivo'),
        ('usuarios', '0015_pagopension_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciataller',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.competencia', verbose_name='Competencia Evaluada'),
        ),
        migrations.AddField(
            model_name='evidenciataller',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.objetivo', verbose_name='Objetivo Evaluado'),
        ),
    ]
