# Generated by Django 5.0.14 on 2026-09-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de la Visita o Sesión')),
                ('tipo_seguimiento', models.CharField(choices=[('Presencial Aula', 'Visita Presencial en Aula de Clase'), ('Revision Taller', 'Revisión Presencial de Ambientes / Taller'), ('Reunion Colegio', 'Reunión con Rectoría / Docente Enlace'), ('Virtual', 'Sesión de Acompañamiento Virtual'), ('Comite', 'Comité de Seguimiento Formativo')], default='Presencial Aula', max_length=30, verbose_name='Tipo de Seguimiento')),
                ('observaciones', models.TextField(verbose_name='Diagnóstico y Observaciones Pedagógicas / Técnicas')),
                ('compromisos', models.TextField(blank=True, null=True, verbose_name='Compromisos y Plan de Acción Acordado')),
                ('fecha_verificacion', models.DateField(blank=True, null=True, verbose_name='Fecha Límite para Verificar Cumplimiento de Compromisos')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='actas_seguimiento/%Y/%m/', verbose_name='Acta de Visita Firmada o Soporte Escaneado (PDF/Imagen)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo del Registro (Inmutable)')),
                ('ficha', models.ForeignKey(help_text='Ficha técnica a la cual se realizó el acompañamiento.', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='academico.ficha', verbose_name='Ficha de Media Técnica')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Instructor que Realizó la Visita')),
                ('matricula', models.ForeignKey(blank=True, help_text='Dejar vacío si el seguimiento fue general para todo el grupo de la ficha.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_individuales', to='academico.matricula', verbose_name='Aprendiz Específico (Opcional)')),
            ],
            options={
                'verbose_name': 'Bitácora de Seguimiento',
                'verbose_name_plural': 'Bitácoras de Seguimiento',
                'ordering': ['-fecha_visita', '-fecha_registro'],
            },
        ),
    ]
