# Generated by Django 5.0.14 on 2026-09-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_asistenciaaprendiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraseguimiento',
            name='firma_docente_enlace',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_actas/%Y/%m/', verbose_name='Firma del docente enlace'),
        ),
        migrations.AddField(
            model_name='bitacoraseguimiento',
            name='firma_instructor',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_actas/%Y/%m/', verbose_name='Firma del instructor SENA'),
        ),
    ]
