# Generated by Django 5.0.14 on 2026-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_bitacoraseguimiento_firma_docente_enlace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraseguimiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud GPS de la visita'),
        ),
        migrations.AddField(
            model_name='bitacoraseguimiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud GPS de la visita'),
        ),
        migrations.AddField(
            model_name='bitacoraseguimiento',
            name='precision_gps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precisión GPS en metros'),
        ),
    ]
