# Generated by Django 5.0.14 on 2026-09-15 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_bitacoraseguimiento_latitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Contenido del Mensaje o Aviso')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Envio')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='seguimiento.bitacoraseguimiento', verbose_name='Bitácora / Caso de Seguimiento')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje de Seguimiento',
                'verbose_name_plural': 'Mensajes de Seguimiento',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
