# Generated by Django 5.0.14 on 2026-09-19 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_horarioficha_options'),
        ('seguimiento', '0005_mensajeseguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título de la Notificación')),
                ('mensaje', models.TextField(verbose_name='Mensaje Detallado')),
                ('enlace', models.CharField(blank=True, default='', max_length=255, verbose_name='Enlace de Acción Directa')),
                ('tipo', models.CharField(choices=[('info', 'Información General'), ('success', 'Éxito / Aprobación'), ('warning', 'Atención / Alerta'), ('danger', 'Urgente / Deficiente')], default='info', max_length=20, verbose_name='Tipo de Notificación')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Notificación Leída?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Notificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación Institucional',
                'verbose_name_plural': 'Notificaciones Institucionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=160, verbose_name='Acción Realizada')),
                ('modulo', models.CharField(max_length=80, verbose_name='Módulo Institucional')),
                ('detalles', models.TextField(blank=True, default='', verbose_name='Detalles Técnicos y Datos Modificados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP de Origen')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de la Acción')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Ejecutor')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto de la Solicitud')),
                ('categoria', models.CharField(choices=[('Academica', 'Académica (Novedades de formación)'), ('Certificacion', 'Certificación y Paz y Salvo'), ('Matricula', 'Matrícula y Traslados'), ('Ficha', 'Cambio o Novedad de Ficha'), ('Documentacion', 'Entrega o Solicitud de Documentación'), ('Horario', 'Ajuste de Horario / Ambientes'), ('Novedad', 'Novedad de Deserción / Aplazamiento'), ('Otra', 'Otra Consulta Institucional')], default='Academica', max_length=50, verbose_name='Categoría del Trámite')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=20, verbose_name='Prioridad')),
                ('mensaje', models.TextField(verbose_name='Descripción Detallada de la Solicitud')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes_secretaria/%Y/%m/', verbose_name='Documento o Soporte Adjunto (PDF/Imagen)')),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada (Pendiente de Radicación)'), ('RECIBIDA', 'Recibida por Secretaría'), ('EN_REVISION', 'En Revisión / Trámite'), ('RESPONDIDA', 'Respondida'), ('CERRADA', 'Cerrada / Finalizada')], default='ENVIADA', max_length=20, verbose_name='Estado de la Solicitud')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_secretaria', to=settings.AUTH_USER_MODEL, verbose_name='Aprendiz Solicitante')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_secretaria', to='academico.ficha', verbose_name='Ficha Relacionada')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Responsable (Secretaría/Coordinación)')),
            ],
            options={
                'verbose_name': 'Solicitud a Secretaría',
                'verbose_name_plural': 'Solicitudes a Secretaría',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Contenido de la Respuesta')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='respuestas_secretaria/%Y/%m/', verbose_name='Documento Adjunto de Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Respuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_solicitud', to=settings.AUTH_USER_MODEL, verbose_name='Autor de la Respuesta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='seguimiento.solicitudsecretaria', verbose_name='Solicitud Asociada')),
            ],
            options={
                'verbose_name': 'Respuesta a Solicitud',
                'verbose_name_plural': 'Respuestas a Solicitudes',
                'ordering': ['fecha_respuesta'],
            },
        ),
    ]
