# Generated by Django 5.0.14 on 2026-09-19 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_documentoinstitucional_logroaprendiz_and_more'),
        ('seguimiento', '0006_notificacion_registroauditoria_solicitudsecretaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='NIT / Identificación Tributaria')),
                ('representante_legal', models.CharField(blank=True, max_length=150, verbose_name='Representante Legal')),
                ('contacto_nombre', models.CharField(max_length=150, verbose_name='Persona de Contacto')),
                ('contacto_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo de Contacto')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('contacto_telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección de la Sede')),
                ('municipio', models.CharField(default='Santa Marta', max_length=100, verbose_name='Municipio')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Convenio Activo?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa en Convenio',
                'verbose_name_plural': 'Empresas en Convenio',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='CasoAlertaTemprana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('inasistencia', 'Inasistencia Reiterada'), ('academica', 'Rendimiento Académico RAP'), ('evidencias', 'Evidencias Formativas Pendientes'), ('compromiso_vencido', 'Compromiso Vencido sin Verificar'), ('multidisciplinaria', 'Riesgo Integral Multi-factor')], max_length=40, verbose_name='Tipo de Alerta')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio / Preventivo'), ('ALTO', 'Alto / Crítico')], default='MEDIO', max_length=20, verbose_name='Nivel de Riesgo')),
                ('puntuacion_riesgo', models.DecimalField(decimal_places=1, default=50.0, max_digits=5, verbose_name='Puntuación de Riesgo (%)')),
                ('factores_detectados', models.TextField(verbose_name='Factores Explicables Detectados')),
                ('estado', models.CharField(choices=[('ALERTA', 'Alerta Generada'), ('REVISION', 'En Revisión'), ('ASIGNACION', 'Asignación de Responsable'), ('INTERVENCION', 'Intervención / Citación'), ('COMPROMISO', 'Plan de Compromisos'), ('SEGUIMIENTO', 'En Seguimiento'), ('RESULTADO', 'Evaluación de Resultados'), ('CERRADO', 'Caso Cerrado')], default='ALERTA', max_length=25, verbose_name='Fase del Flujo')),
                ('plan_accion', models.TextField(blank=True, verbose_name='Plan de Acción e Intervención')),
                ('resultado_final', models.TextField(blank=True, verbose_name='Resultado del Caso')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_alerta', to='academico.matricula', verbose_name='Aprendiz Vinculado')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_alerta_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario / Instructor Responsable')),
            ],
            options={
                'verbose_name': 'Caso de Alerta Temprana',
                'verbose_name_plural': 'Casos de Alerta Temprana',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='CompromisoFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Compromiso')),
                ('descripcion', models.TextField(verbose_name='Descripción y Plan de Acción')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CUMPLIDO', 'Cumplido'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('evidencia_cumplimiento', models.FileField(blank=True, null=True, upload_to='compromisos_evidencias/%Y/%m/', verbose_name='Evidencia de Cumplimiento (PDF / Imagen)')),
                ('observaciones_verificacion', models.TextField(blank=True, verbose_name='Retroalimentación del Instructor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bitacora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_asociados', to='seguimiento.bitacoraseguimiento', verbose_name='Bitácora de Origen (Opcional)')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Instructor Verificador')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos_formativos', to='academico.matricula', verbose_name='Aprendiz Responsable')),
            ],
            options={
                'verbose_name': 'Compromiso Formativo',
                'verbose_name_plural': 'Compromisos Formativos',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_asistencia_preventiva', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='% Asistencia Alerta Preventiva')),
                ('umbral_asistencia_critica', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='% Asistencia Alerta Crítica')),
                ('max_evidencias_pendientes', models.PositiveIntegerField(default=3, verbose_name='Máx. Evidencias Pendientes')),
                ('dias_inactividad_alerta', models.PositiveIntegerField(default=10, verbose_name='Días de Inactividad para Alerta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Alertas Tempranas',
                'verbose_name_plural': 'Configuraciones de Alertas Tempranas',
            },
        ),
        migrations.CreateModel(
            name='EtapaProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Contrato de Aprendizaje', 'Contrato de Aprendizaje'), ('Pasantia', 'Pasantía Institucional / Empresarial'), ('Vinculo Laboral', 'Vínculo Laboral o Contractual'), ('Proyecto Productivo', 'Proyecto Productivo de Innovación'), ('Monitoria', 'Monitoría Académica SENA')], default='Contrato de Aprendizaje', max_length=40, verbose_name='Modalidad SENA')),
                ('tutor_empresarial', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Tutor Empresarial')),
                ('tutor_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo del Tutor')),
                ('tutor_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo del Tutor')),
                ('tutor_telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono del Tutor')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Culminación')),
                ('estado', models.CharField(choices=[('POR_INICIAR', 'Por Iniciar / En Trámite de Convenio'), ('EN_DESARROLLO', 'En Desarrollo Activo'), ('FINALIZADA', 'Finalizada y Aprobada'), ('NOVEDAD', 'Novedad de Aplazamiento o Cancelación')], default='POR_INICIAR', max_length=25, verbose_name='Estado de la Etapa')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de la Coordinación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices_vinculados', to='seguimiento.empresaconvenio', verbose_name='Empresa Patrocinadora / Co-formadora')),
                ('instructor_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprendices_seguimiento_productivo', to=settings.AUTH_USER_MODEL, verbose_name='Instructor de Seguimiento Asignado')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etapa_productiva', to='academico.matricula', verbose_name='Aprendiz en Formación')),
            ],
            options={
                'verbose_name': 'Etapa Productiva de Aprendiz',
                'verbose_name_plural': 'Etapas Productivas de Aprendices',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraEtapaProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_visita', models.PositiveSmallIntegerField(choices=[(1, 'Visita Inicial (Concertación de Plan de Trabajo)'), (2, 'Visita Intermedia (Evaluación Parcial de Desempeño)'), (3, 'Visita Final (Evaluación y Cierre de Etapa Productiva)')], default=1, verbose_name='Número de Visita')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de la Visita')),
                ('actividades_desarrolladas', models.TextField(verbose_name='Actividades Técnicas Desarrolladas por el Aprendiz')),
                ('concepto_evaluativo', models.CharField(choices=[('SATISFACTORIO', 'Cumplimiento Satisfactorio'), ('POR_MEJORAR', 'Requiere Plan de Mejoramiento'), ('DEFICIENTE', 'No Cumple / Novedad')], default='SATISFACTORIO', max_length=25, verbose_name='Concepto de la Visita')),
                ('observaciones_tutor', models.TextField(blank=True, verbose_name='Observaciones del Tutor Empresarial')),
                ('observaciones_instructor', models.TextField(blank=True, verbose_name='Recomendaciones del Instructor SENA')),
                ('acta_soporte_pdf', models.FileField(blank=True, null=True, upload_to='etapa_productiva_actas/%Y/%m/', verbose_name='Acta de Visita Firmada (Formato F023 SENA)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Instructor Evaluador')),
                ('etapa_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='seguimiento.etapaproductiva', verbose_name='Expediente de Etapa Productiva')),
            ],
            options={
                'verbose_name': 'Bitácora de Etapa Productiva',
                'verbose_name_plural': 'Bitácoras de Etapa Productiva',
                'ordering': ['etapa_productiva', 'numero_visita'],
            },
        ),
    ]
