# Generated by Django 5.0.14 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_empresaconvenio_casoalertatemprana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraseguimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Realizado', 'Realizado')], default='Realizado', max_length=20, verbose_name='Estado del Seguimiento'),
        ),
    ]
