# Generated by Django 5.0.14 on 2026-09-22 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_programaformacion_convenio_and_more'),
        ('convenios', '0002_conveniosena_institucion_educativa_beneficioconvenio'),
        ('instituciones', '0004_contactoinstitucional_observacioninstitucional'),
        ('seguimiento', '0008_bitacoraseguimiento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('tipo', models.CharField(choices=[('Convenio', 'Convenio Formal y Anexos'), ('Acta', 'Acta de Reunión / Visita'), ('Certificación', 'Certificación Institucional'), ('Formato Oficial SENA', 'Formato Oficial SENA (PE-04 / F023)'), ('Guía Pedagógica', 'Guía de Aprendizaje Pedagógica'), ('Ficha Técnica', 'Ficha Técnica del Programa'), ('Resolución', 'Resolución Rectoral o SENA'), ('Reglamento', 'Reglamento y Circulares'), ('Otro', 'Otro Documento')], default='Acta', max_length=60, verbose_name='Clasificación del Documento')),
                ('archivo', models.FileField(upload_to='documentos_admin/%Y/%m/', verbose_name='Archivo Digital')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Contenido')),
                ('fecha_documento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del Documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Carga')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_admin', to='convenios.conveniosena', verbose_name='Convenio Asociado')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_admin', to='instituciones.institucioneducativa', verbose_name='Colegio / Institución Asociada')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_admin', to='academico.programaformacion', verbose_name='Programa Técnico Asociado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_admin_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario que Cargó el Archivo')),
            ],
            options={
                'verbose_name': 'Documento Administrativo',
                'verbose_name_plural': 'Biblioteca Documental Administrativa',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('tipo_evento', models.CharField(choices=[('Reunión', 'Reunión Institucional'), ('Seguimiento', 'Seguimiento Administrativo'), ('Vencimiento', 'Vencimiento de Convenio'), ('Actividad', 'Actividad Pedagógica / Visita'), ('Comité', 'Comité de Evaluación'), ('Capacitación', 'Jornada de Capacitación'), ('Otro', 'Otro Evento')], default='Reunión', max_length=50, verbose_name='Tipo de Evento')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Detalles o Agenda del Evento')),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En Curso', 'En Curso'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=30, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='convenios.conveniosena', verbose_name='Convenio Vinculado (Opcional)')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='instituciones.institucioneducativa', verbose_name='Colegio / Institución Vinculada')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Responsable')),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto del Seguimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción y Contexto de la Tarea')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=25, verbose_name='Estado Actual')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Registro')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Cumplimiento')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado / Gestión Lograda')),
                ('proxima_accion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Próxima Acción Inmediata')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_admin', to='convenios.conveniosena', verbose_name='Convenio Asociado (Opcional)')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_admin', to='instituciones.institucioneducativa', verbose_name='Colegio / Institución Educativa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_admin_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Responsable')),
            ],
            options={
                'verbose_name': 'Seguimiento Administrativo',
                'verbose_name_plural': 'Seguimientos Administrativos',
                'ordering': ['-fecha_limite', '-fecha_registro'],
            },
        ),
    ]
