# Generated by Django 5.0.14 on 2026-09-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_matricula_seccion'),
        ('seguimiento', '0009_documentoadministrativo_eventocalendario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estamento_destinatario', models.CharField(choices=[('Toda', 'Toda la Comunidad Educativa'), ('Docentes', 'Cuerpo Docente'), ('Estudiantes', 'Estudiantes'), ('Familias', 'Acudientes y Familias')], default='Toda', max_length=50, verbose_name='Estamento Destinatario')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto de la Circular')),
                ('mensaje', models.TextField(verbose_name='Contenido de la Comunicación')),
                ('urgente', models.BooleanField(default=False, verbose_name='¿Notificación Prioritaria / Urgente?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Emisión')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_especificos', to='academico.ficha', verbose_name='Curso o Grupo (Opcional)')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Emisor')),
            ],
            options={
                'verbose_name': 'Comunicado Escolar',
                'verbose_name_plural': 'Comunicados Escolares',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
