# Generated by Django 5.0.14 on 2026-09-28 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0010_comunicadoescolar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadoescolar',
            name='estudiante_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_directos', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante Específico (Opcional)'),
        ),
        migrations.AlterField(
            model_name='asistenciaaprendiz',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Ausencia justificada'), ('T', 'Tardanza')], default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
