# Generated by Django 5.0.14 on 2026-09-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_tareaclase_periodo'),
        ('seguimiento', '0011_comunicadoescolar_estudiante_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaaprendiz',
            name='carga_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_sesion', to='academico.cargaacademica', verbose_name='Carga Académica / Asignatura'),
        ),
        migrations.AddField(
            model_name='asistenciaaprendiz',
            name='periodo',
            field=models.CharField(blank=True, default='Periodo 1', max_length=50, verbose_name='Periodo Académico'),
        ),
    ]
