# Generated by Django 5.0.14 on 2026-09-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(help_text='Código único asignado por el DANE / MEN al colegio.', max_length=20, unique=True, verbose_name='Código DANE Oficial')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Oficial de la Institución Educativa')),
                ('municipio', models.CharField(help_text='Municipio donde está ubicada la sede principal.', max_length=100, verbose_name='Municipio del Magdalena')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Física')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Institucional')),
                ('rector_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Rector(a)')),
                ('enlace_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Docente Enlace / Coordinador')),
                ('enlace_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Docente Enlace')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Convenio Activo y Vigente?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro en SINETEC')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'ordering': ['municipio', 'nombre'],
            },
        ),
    ]
