# Generated by Django 5.0.14 on 2026-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='enlace_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Docente Enlace'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='rector_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Rector(a)'),
        ),
    ]
