# Generated by Django 5.0.14 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_institucioneducativa_enlace_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Institucional'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Generales'),
        ),
    ]
