# Generated by Django 5.0.14 on 2026-09-22 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_conveniosena_institucion_educativa_beneficioconvenio'),
        ('instituciones', '0003_institucioneducativa_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellido(s)')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo o Función')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / Celular')),
                ('tipo', models.CharField(choices=[('Rector', 'Rector(a)'), ('Coordinador', 'Coordinador(a) Académico'), ('Encargado Convenio', 'Encargado(a) del Convenio SENA'), ('Docente Enlace', 'Docente Enlace de Media Técnica'), ('Administrativo', 'Personal Administrativo'), ('Secretaria', 'Secretaría del Colegio'), ('Orientador', 'Orientador(a) Escolar'), ('Otro', 'Otro Contacto Institucional')], default='Coordinador', max_length=50, verbose_name='Tipo de Contacto')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Horario de Atención')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='instituciones.institucioneducativa', verbose_name='Colegio / Institución')),
            ],
            options={
                'verbose_name': 'Contacto Institucional',
                'verbose_name_plural': 'Contactos Institucionales',
                'ordering': ['institucion', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del Registro')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Asunto')),
                ('tipo', models.CharField(choices=[('Reunión', 'Reunión Institucional'), ('Seguimiento', 'Seguimiento Administrativo'), ('Acuerdo', 'Acuerdo / Compromiso'), ('Novedad', 'Novedad Institucional'), ('Antecedente', 'Antecedente Histórico'), ('Compromiso', 'Compromiso Formal'), ('Incidencia', 'Incidencia / Problema Reportado'), ('Visita', 'Visita Técnica / Protocolaria'), ('Otro', 'Otro Registro')], default='Reunión', max_length=50, verbose_name='Tipo de Observación')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Atendido', 'Atendido / Cumplido'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=25, verbose_name='Estado de Atención')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Límite / Próximo Seguimiento')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado / Conclusiones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_institucionales', to='convenios.conveniosena', verbose_name='Convenio Asociado (Opcional)')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_admin', to='instituciones.institucioneducativa', verbose_name='Colegio / Institución')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Responsable')),
            ],
            options={
                'verbose_name': 'Observación / Antecedente Institucional',
                'verbose_name_plural': 'Observaciones y Antecedentes',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
